### ISSUE TITLE
[epic] MVP of Full Portal/Catalog app: site components, bootstrap app etc (June 2020)

### ISSUE THREAD

**Issue by rufuspollock** [datopian/portal.js#16]
A decoupled data portal frontend built in javascript. See RFC for background: https://github.com/ckan/ideas/blob/master/rfcs/0005-decoupled-frontend.md

## Acceptance criteria

* [x] Analysis written about frontend **See RFC**
* [x] MVP of app using content from both DMS (CKAN e.g. demo.ckan.org) and CMS (e.g. wordpress)
* [ ] `create-portal-app` command and steps to boot a new portal #33 
* [ ] More features
  * [x] Google Analytics
* [ ] Reasonable docs(could reuse http://tech.datopian.com/frontend/ (if any needed))
  * [ ] Features
  * [ ] Getting started (5-10m tutorial)
  * [ ] Booting up
  * [ ] Basic config including add DMS (CKAN) and CMS (wordpress)
  * [ ] How to customize look and feel
  * [ ] How to add a new route
  * [ ] How to deploy
  * [ ] Feature matchup against CKAN current 

## Tasks

* [x] Analysis **DONE**
* [x] Stubbing the project
* [x] Preliminaries: Comparison of next.js vs nuxt.js, research typescript, tests, CI
* [x] MVP of a portal UI i.e. the key components: home, showcase, org pages #9 
* [x] Data layer **See below**
* [x] Integrate CMS (e.g. blog) #32
* [x] create-portal-app script
* [ ] Refactoring of the MVP to move out components and library code
  * [ ] Components
  * [ ] Data Access library
* [ ] More features
  * [ ] Google analytics
  * [ ] i18n
  * [ ] Authentication - #34 
  * [ ] Permissions - #34 
* [ ] Documentation
* [ ] Write up and announce

### Overview

```mermaid
graph TD

bootscript[Boot script]
docs[Documentation]

boot[Boot up] --> mvpsite[MVP of site]
mvpsite --> bootscript
mvpsite --> docs
mvpsite --> morecomp[More Components]
mvpsite --> auth[Authentication]
bootscript --> announce
docs --> announce[Announce]

classDef done fill:#21bf73,stroke:#333,stroke-width:1px;
classDef nearlydone fill:lightgreen,stroke:#333,stroke-width:1px;
classDef inprogress fill:orange,stroke:#333,stroke-width:1px;
classDef next fill:lightblue,stroke:#333,stroke-width:1px;

class boot done;
class mvpsite nearlydone;
class inprogress inprogress;
class bootscript next;
```

### Detailed

```mermaid
graph TD

analysis[Analysis]
stub[Stub]
prelim[Preliminaries]

subgraph MVP of overall app
  analysis --> stub
  stub --> prelim
  prelim --> frontpage[Front page]

subgraph v0.1 MVP of a portal UI #9
  frontpage --> search
  frontpage --> search[Search page]
  search --> showcase[Dataset showcase]
  showcase --> showcase2[Resource showcase]
  search --> cms["CMS integration (Wordpress)"]
  showcase2 --> org[Org page]
end

datalayer[Data layer => GraphQL]

prelim --> datalayer
datalayer --> livesite{Live Site}
cms --> livesite
org --> livesite

end



subgraph Docs
  prelim --> readme[Stub README with install etc]
end

theme

subgraph v1
end

subgraph Docs
end


classDef done fill:#21bf73,stroke:#333,stroke-width:1px;
classDef nearlydone fill:lightgreen,stroke:#333,stroke-width:1px;
classDef inprogress fill:orange,stroke:#333,stroke-width:1px;
classDef next fill:lightblue,stroke:#333,stroke-width:1px;


class stub done;
class prelim done;
class frontpage done;
class datalayer done;
class search done;
class cms done;
class showcase done;
class showcase2 inprogress;
class org next;
```

```mermaid
graph TD

subgraph Key
  done[Done]
  nearlydone[Nearly Done]
  inprogress[In Progress]
  next[Next Up]
end

classDef done fill:#21bf73,stroke:#333,stroke-width:1px;
classDef nearlydone fill:lightgreen,stroke:#333,stroke-width:1px;
classDef inprogress fill:orange,stroke:#333,stroke-width:1px;
classDef next fill:lightblue,stroke:#333,stroke-width:1px;

class done done;
class nearlydone nearlydone;
class inprogress inprogress;
class next next;
```

### Preliminaries

* [x] Choose between javascript and typescript (prob go with typescript) **typescript**
* [x] Choose between next and nuxt **Chose next.js**
* [x] Configure test suite. Recommended to take a look in the libraries libs: Jest, Mocha, Chai.js, and Sinon.js. **Went with Jest**
  * We are adding Cypress for functional tests - see PR here - #26 
* [x] Configuration file for Continuous Integration/Continuous Delivery. - #19 

### Data Layer

* [x] Research options and choose approach #24 **Using Apollo Graphql as internal data layer**
* [x] NextJS working against demo ckan
* [x] Setup Apollo client with CKAN API and manage state from its cache - #29 
* [x] Connect WordPress API to Apollo client - #32 

### Documentation

* [x] Write a README for a new person starting your project
  * [x] Include aspirational getting start (readme drive development) E.g. `create-portal-app`
* [ ] How to customize the look and feel
* [ ] More complex customization
* [ ] Matchup up against current CKAN functionality
  * [ ] Front page
  * [ ] Showcase
    * [ ] Dataset
    * [ ] Resource
  * [ ] Catalog Search
  * [ ] Showcase page
  * [ ] Resource views
  * [ ] Collections (tags)
  * [ ] Organizations
  * [ ] CMS
    * [ ] Blog listing
    * [ ] Blog post
    * [ ] Page

**Comment by anuveyatsu** [comment]
Let's create a separate issue for items outside MVP

**Comment by anuveyatsu** [comment]
@rufuspollock could you pleas clarify a bit about these tasks:

> Refactoring of the MVP to move out components and library code
> * components
> * Data Access library

**Comment by rufuspollock** [comment]
@anuveyatsu 

* Components: factoring out (and documenting) React components (if needed) to a library structure so that you can import in other projects easily.
* Data Access library: ditto for data access library (for CKAN, wordpress etc).

Is that clearer?

**Comment by steveoni** [comment]
While working with the portal js, I was experiencing an error, while trying to view the Dataset resources, as illustrated here #49 . Hence I created a pull request #50 to fix the error

**Comment by steveoni** [comment]
Currently, working on the create-portal-app. I created a package to obtain `portal.js` from Github and install the necessary packages, by specifying either NPM or Yarn. here is the [repo](https://github.com/steveoni/create-portal-app) to the code.

This afternoon I and Thadeu discuss and we find out that we are working on the same thing, Hence some adjustments will be made to my former approach. So Thadeu and I will be working on it.

**Comment by cotts** [comment]
I've created a pull request related to create-portal-app for review #33 -  #52

**Comment by steveoni** [comment]
Pull request #51 adds i18n feature to Portal.js. Currently supporting English and French. All other languages can be added by subsequent users.

**Comment by steveoni** [comment]
Pull requests #54 adds google analytics to Portal.js.

**Comment by rufuspollock** [comment]
FIXED / WONTFIX. A large portion of this was done and is in https://github.com/datopian/portal.js/tree/master/examples/catalog. For parts remaining these will probably be addressed in examples and docs and so merit somewhat different issue so closing this for now.
