### ISSUE TITLE
Setup integration tests using cypress

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/portal.js#21]
## Acceptance criteria

* [x] I can run `yarn e2e` and it'd run integration tests
* [x] We have tests for all existing pages
* [x] ? Run via Travis or similar CI

## Tasks

* [x] Install and setup Cypress
* [x] Write tests
* [x] Setup CI

**Comment by anuveyatsu** [comment]
Blocked by PR #26

**Comment by rufuspollock** [comment]
FIXED. We have tests fo the home page, search page. Still no test for Dataset page (will assume that will come as part of e.g. #12 )
