### ISSUE TITLE
Design boot page for new app

### ISSUE THREAD

**Issue by monikappv** [datopian/portal.js#35]
A landing page like nextjs one / rails when you boot a new app
- create-portal-app
- This would be very plain, still use our styling and give you instructions

![nextjs_boot-app](https://user-images.githubusercontent.com/56799741/86656962-8acd7b80-bff0-11ea-84ad-56e6e838ad4f.png)

![rails_boot-app](https://user-images.githubusercontent.com/56799741/86656979-8d2fd580-bff0-11ea-9372-623a16d944a4.png)

## Acceptance

* [x] mockup of boot page **DONE see https://xd.adobe.com/view/3040c464-6cc2-4fc0-b808-bd0a436e0014-6513/**

## Tasks

* [x] mock some rough boot page structure
* [x] take elements from the hero section design
* [x] play around with different options
* [x] pick the best ones
* [x] get feedback
* [x] implement changes
* [x] polish off

## Outcome

1.

<img width="467" alt="2" src="https://user-images.githubusercontent.com/56799741/86656793-67a2cc00-bff0-11ea-88e9-76f4a9af575c.PNG">

2. 

<img width="467" alt="4" src="https://user-images.githubusercontent.com/56799741/86656810-6b365300-bff0-11ea-949a-da23f6cd8673.PNG">

3.

<img width="471" alt="6" src="https://user-images.githubusercontent.com/56799741/86656836-70939d80-bff0-11ea-9a5f-16e824031dd8.PNG">

4. 

<img width="467" alt="7" src="https://user-images.githubusercontent.com/56799741/86656874-78534200-bff0-11ea-879d-96e340adfb3a.PNG">

**Comment by monikappv** [comment]
@rufuspollock here as well.. please have a look and let me know what you think

**Comment by rufuspollock** [comment]
@monikappv generally look good. these are pasted a bit too small to actually compare - other than the layout. Could you maybe share the XD with these side by side for comparison. You could also add a bit of info e.g. fonts etc. (and maybe add thatinfo to the title for each of them eg..

```
### 4. Tweak to X with Inconsolata font

```

**Comment by monikappv** [comment]
@rufuspollock here's the design that we worked on during the call yesterday 
https://xd.adobe.com/view/3040c464-6cc2-4fc0-b808-bd0a436e0014-6513/

any improvement suggestions?

**Comment by rufuspollock** [comment]
@monikappv looks good for now ...

**Comment by rufuspollock** [comment]
FIXED. We have a finalized design (see description link).
