### ISSUE TITLE
Design logo with air balloon

### ISSUE THREAD

**Issue by monikappv** [datopian/portal.js#36]
## Acceptance

* [x] portal logo

## Tasks

* [x] design logos
* [x] pick a few different options
  * [x] different font styles
  * [x] air balloon instead of O
* [x] upload them here
* [x] get feedback
* [x] implement changes
* [x] polish off

## Some options

1.
<img width="188" alt="1" src="https://user-images.githubusercontent.com/56799741/86763667-293cf980-c050-11ea-8c79-b7a37c18b73b.PNG">
2.
<img width="192" alt="2" src="https://user-images.githubusercontent.com/56799741/86763675-29d59000-c050-11ea-831a-ad916c825441.PNG">
3. 
<img width="207" alt="3" src="https://user-images.githubusercontent.com/56799741/86763677-2a6e2680-c050-11ea-9c12-c62f34e8cecd.PNG">
4.
<img width="186" alt="4" src="https://user-images.githubusercontent.com/56799741/86763678-2a6e2680-c050-11ea-948a-cb2708a530ac.PNG">
5.
<img width="195" alt="6" src="https://user-images.githubusercontent.com/56799741/86763679-2b06bd00-c050-11ea-96ed-2a88537382d8.PNG">
6.
<img width="187" alt="7" src="https://user-images.githubusercontent.com/56799741/86763681-2b06bd00-c050-11ea-90e0-b8f8d995c231.PNG">

## New suggestions

1.
<img width="217" alt="1" src="https://user-images.githubusercontent.com/56799741/87051866-cc387380-c208-11ea-8ed8-933561b05fb4.PNG">
2.
<img width="203" alt="2" src="https://user-images.githubusercontent.com/56799741/87051869-ccd10a00-c208-11ea-9a75-61a3a21fb21f.PNG">
3.
<img width="208" alt="3" src="https://user-images.githubusercontent.com/56799741/87051878-ce023700-c208-11ea-9c90-a20cb9255f09.PNG">
4.
<img width="207" alt="4" src="https://user-images.githubusercontent.com/56799741/87051882-ce9acd80-c208-11ea-82e5-73b6ce13bc0c.PNG">
5.
<img width="212" alt="6_2" src="https://user-images.githubusercontent.com/56799741/87052177-289b9300-c209-11ea-8911-9ab6d8fc6fa0.PNG">
6.
<img width="258" alt="8" src="https://user-images.githubusercontent.com/56799741/87051855-c9d61980-c208-11ea-91e6-bc254495e7d0.PNG">

---

## THE Logo

![AquireLogo_](https://user-images.githubusercontent.com/56799741/109360963-bf988680-7890-11eb-8dba-a244fb9c614b.PNG)

Font: [Aquire Light](https://www.dafontfree.io/aquire-free-font/)
Logo Files: See [Portal.JS Assets folder](https://drive.google.com/drive/u/1/folders/1mFevPKUtzsd1NH_EZYAyQ-eAGhxtjlv1) on Gdrive

**Comment by monikappv** [comment]
@rufuspollock and here as well... I would also try other font styles but maybe some feedback about these would help me get into the right direction

**Comment by rufuspollock** [comment]
@monikappv i think you want the balloon to be much simpler and much more integrated with text. Imagine how this will look in an actual website in e.g. the navbar. Lots of detail just won't show up.

Also in terms of vertical space i think you want the balloon within the vertical height of the text.

**Comment by monikappv** [comment]
@rufuspollock tried out simpler balloon versions - have added a new section called `new suggestions` - please have a look..

**Comment by rufuspollock** [comment]
@monikappv the original balloon had a nice roundedness and not such the new ones are much simpler. Maybe we just go with original no.4 and just see how it scales down - we may have to take out some detail at lower scale. Also what about adding the .js like we discussed. I also think playing with the font is good - and maybe something sans serif.

**Comment by rufuspollock** [comment]
@monikappv how is this going?

**Comment by monikappv** [comment]
@rufuspollock 

## Update

* left the balloon as it is in no.4
* we could remove the people as it scales down (?) or make the grey part black as it is not so visible when it scales down
* added the .js
* tried out few sans serif fonts

## Suggestions

1. Roboto Slab

<img width="247" alt="1" src="https://user-images.githubusercontent.com/56799741/87684805-58a7e080-c78b-11ea-8d30-2b9bdd9f9c09.PNG">

2. Avantgarde 

<img width="239" alt="avantgarde" src="https://user-images.githubusercontent.com/56799741/87684830-5f365800-c78b-11ea-8790-2f3ad538fdf2.PNG">

3. DIN

<img width="252" alt="DIN" src="https://user-images.githubusercontent.com/56799741/87684840-62c9df00-c78b-11ea-80f4-a9713bb1a5a4.PNG">

4. Kontora (all uppercase)

<img width="234" alt="kontora" src="https://user-images.githubusercontent.com/56799741/87684924-7aa16300-c78b-11ea-8061-2eb6fe17631c.PNG">

5. Kontora (ballon more integrated)

<img width="212" alt="kontora-2-balloon" src="https://user-images.githubusercontent.com/56799741/87684956-82610780-c78b-11ea-861b-62293e9c183e.PNG">

6. Kontora (normal)

<img width="354" alt="kontora-3-normal" src="https://user-images.githubusercontent.com/56799741/87684986-8bea6f80-c78b-11ea-88fe-5625c7b9a00c.PNG">

7. Montserrat

<img width="222" alt="montserrat" src="https://user-images.githubusercontent.com/56799741/87687303-3fecfa00-c78e-11ea-81ed-b2a3f9c2d51c.PNG">

8. Noyh

<img width="327" alt="noyh" src="https://user-images.githubusercontent.com/56799741/87687332-48453500-c78e-11ea-9658-96e562bd069a.PNG">

9. Open Sans

<img width="233" alt="open-sans" src="https://user-images.githubusercontent.com/56799741/87687354-4f6c4300-c78e-11ea-9547-a81adb6046b9.PNG">

10. Wavehouse 

<img width="252" alt="wavehouse" src="https://user-images.githubusercontent.com/56799741/87687370-5430f700-c78e-11ea-828c-a0290b537710.PNG">

**Comment by rufuspollock** [comment]
@monikappv so i def think we want lowercase rather than upper case ie. Portal not PORTAL because the balloon O fits better. I think we also want something very clean on the letters e.g. Din looks better than Roboto Slab (so prob sans serif). Could we do a few more variants on that - i don't yet see anything that jumps out. Let's chat quickly i think (ps can you share the XD)

**Comment by monikappv** [comment]
@rufuspollock 

On the call we discussed the following two points:
* the bottom of the balloon should be aligned with the text but also floating on it a bit
* the text should be clean / have less details e.g. DIN

So here are three final suggestions following these principles

<img width="360" alt="montserrat" src="https://user-images.githubusercontent.com/56799741/87847130-35417a80-c8de-11ea-9130-16e3a92258d5.PNG">

<img width="207" alt="opensans" src="https://user-images.githubusercontent.com/56799741/87847134-37a3d480-c8de-11ea-8e98-bbe66ec37510.PNG">

<img width="235" alt="fontawesome" src="https://user-images.githubusercontent.com/56799741/87847136-3b375b80-c8de-11ea-8177-844a578ee614.PNG">

**NB:** Due to missing fonts in XD also on my end, we thought that we were looking at Montserrat when Adobe XD was actually automatically replacing *Montserrat* with *FontAwesome* (option 3 above) --> **long story short** = what we picked was *FontAwesome* and not *Montserrat*.

**Comment by rufuspollock** [comment]
@monikappv could you share the svg and png of this one (and, perhaps separately, details of the font plus separately the balloon on its own)

![](https://user-images.githubusercontent.com/56799741/87051855-c9d61980-c208-11ea-91e6-bc254495e7d0.PNG)

(PS: think this looks awesome - not sure how i missed it first time round ...)

**Comment by monikappv** [comment]
@rufuspollock 

**Font:** [Aquire Light](https://www.dafontfree.io/aquire-free-font/)
**Logo files:** See [Portal.JS Assets folder](https://drive.google.com/drive/u/1/folders/1mFevPKUtzsd1NH_EZYAyQ-eAGhxtjlv1) on Gdrive

**Comment by rufuspollock** [comment]
👍 🙏

**Comment by rufuspollock** [comment]
FIXED. We have a final logo.
