### ISSUE TITLE
Convert to monorepo

### ISSUE THREAD

**Issue by rufuspollock** [datopian/portal.js#38]
With addition of `create-portal-app` it makes sense to move to a monorepo setup.

We will use yarn workspaces and, possibly in future, Lerna.

## Acceptance

* [ ] What is currently in root is in `packages/portal`
* [ ] Have root readme (symlinked from packages/portal)
* [ ] Have root `package.json` setup
* [ ] Have `lerna` setup

## Tasks

* [x] Create `packages`
* [x] Move current code into `packages/portal`
  * [ ] Keep tests in one central location at root (a la next.js)?
* [ ] Root setup
  * [ ] Create a root package.json in wordspace mode
  * [ ] Symlink the README from`packages/portal` into the root
* [ ] Check everything passes
  * [ ] Fix test links

FUTURE

* [ ] ? move `components` out of portal into `portal-components` package (or even split them up more)

## Analysis

* monorepos (for portal.js): Let's use yarn support for monorepos
  * https://classic.yarnpkg.com/en/docs/workspaces/
  * Will require us to refactor base stuff into package ...
* https://medium.com/hy-vee-engineering/creating-a-monorepo-with-lerna-yarn-workspaces-cf163908965d

**Comment by rufuspollock** [comment]
@abhishekgahlot will complete by friday COP.
