### ISSUE TITLE
Update theme of default app

### ISSUE THREAD

**Issue by rufuspollock** [datopian/portal.js#40]
Apply theme from home page mockup in #30 to default app (currently in root folder and will move to `packages/portal/` with monorepo #38 

### Estimation
2d

## Acceptance

* [x] When I create a portal with the default theme it looks like the mockup in #30 (on front page) and uses those fonts etc elsewhere 
* [x] No hard-coded color values (we are using tailwind ...)

## Tasks

- [x] Install current setup
- [x] Get access to XD
- [x] Define colors and font size in tailwind config / in css
- [x] Setup theme and stylesheets based on theme

**Comment by tavareshansen** [comment]
@rufuspollock @abhishekgahlot This issue is ready for review.
Please find attached PR and review it.
