### ISSUE TITLE
Refactoring Code as of  July 2020

### ISSUE THREAD

**Issue by abhishekgahlot** [datopian/portal.js#41]
There are a few things we could do to refactor the codebase and set up a proper style guide.

## Estimation
4d
## Acceptance

* [x] We have code linting and prettifying which is checked automatically as part of CI
* [x] We have shared components that are reused
* [x] Typescript set up with proper types
* [x] No `map` using index as key
* [x] Create custom hooks/Context API, and replace `initializeApollo` with it

## Tasks

- [x] atm no shared components. We can define shared components like input, forms, buttons, etc.
- [x] There's no gql schema management system. Right now, it has a gql query defined in each component file, which should be managed in one place.
- [x] Why don't we use lazy hooks method like useLazyQuery as well as useQuery?
- [x] It seems like they're trying to use typescript, but no types defined. Actually, it's not typescript.
- [x] I can see a bunch of duplicated code, which we can refactor by using well-structured data.
e.g. /components/dataset/About.tsx => We can define table columns/rows.
- [x] Implement code linting e.g. use eslint?
- [x] Do not use array index as key when rendering list
- [x] Create and use custom hooks/Context API for managing 3rd party libraries. e.g. apollo-client initializer defined in `lib`

**Comment by abhishekgahlot** [comment]
cc @azfullstack2258

**Comment by rufuspollock** [comment]
@abhishekgahlot can we get details of this issue.

**Comment by azfullstack2258** [comment]
- There's no gql schema management system. Right now, it has a gql query defined in each component file, which should be managed in one place.
- Why don't we use lazy hooks method like useLazyQuery as well as useQuery?
- It seems like they're trying to use typescript, but no types defined. Actually, it's not typescript.
- I can see a bunch of duplicated code, which we can refactor by using well-structured data.
e.g. /components/dataset/About.tsx => We can define table columns/rows.
- It has no theme setup, no stylesheets defined.
- No shared components. We can define shared components like input, forms, button, etc.
- In terms of coding style, why don't we use eslint?

**Comment by abhishekgahlot** [comment]
@rufuspollock we have added the checklist here.

**Comment by rufuspollock** [comment]
@tavareshansen can you please estimate this item in d.

**Comment by tavareshansen** [comment]
> @tavareshansen can you please estimate this item in d.

@rufuspollock sure.

**Comment by abhishekgahlot** [comment]
@tavareshansen Can we also check the items that are merged into this PR, I am not sure if the PR had everything mentioned above?

**Comment by tavareshansen** [comment]
yes, I did.

**Comment by abhishekgahlot** [comment]
Cool thanks as this PR requires another PR to be updated which is #42 .

**Comment by abhishekgahlot** [comment]
The PR has been merged so the issue has been automatically closed.
