### ISSUE TITLE
Move portal-experiment into portal and refactor

### ISSUE THREAD

**Issue by risenW** [datopian/portal.js#59]
Move and refactor [portal-experiment](https://github.com/datopian/portal-experiment) into[ portal.js](https://github.com/datopian/portal.js)

We already have older `packages/portal` which is currently more of an example of a full data catalog site running on nextjs. We want to keep this and move it to `examples/catalog`

Our new `portal` experiment should then become the main `portal` package in `packages/portal` so we can focus on developing there. 

## Acceptance

* [x] `packages/portal` moved to examples/catalog **DONE**
* [x] I have portal-experiment integrated into portal.js repo **DONE. located at `packages/portal`. Have also integrated the CLI into that package.**
* [x] updated main README to reflect this **DONE. Main README is stubbed atm**

## Task

* [x]  Agree on repo we are using **DONE.** We agreed to move [portal-experiment](https://github.com/datopian/portal-experiment) into[ portal.js](https://github.com/datopian/portal.js)
* [x]  Clean up the portal repo
  * [x]  Move packages/portal to examples/catalog
  * [x]  Refactor README to explain this is an example
  * [x]  Reboot portal sub package with README

**Comment by rufuspollock** [comment]
FIXED. All merged in (see acceptance).
