### ISSUE TITLE
Move packages/portal content to root directory

### ISSUE THREAD

**Issue by risenW** [datopian/portal.js#68]
Vercel build by default looks for the pages folder in the root directory when building a nextjs app. With our current repo structure, vercel build is failing with the error:

<img width="1176" alt="Screen Shot 2021-03-08 at 10 47 21 AM" src="https://user-images.githubusercontent.com/29900845/110304495-f5a9d900-7ffb-11eb-937d-b7d8f163233d.png">

## Acceptance
* [x]  I have the packages/portal content in the root directory **Done** https://github.com/datopian/portal.js/pull/69
* [x] Vercel build works without error **Done** https://portal-git-fix-build-error-datopian1.vercel.app/

## Task
* [x]  Move packages/portal content into root directory
