### ISSUE TITLE
Add portal show CLI feature

### ISSUE THREAD

**Issue by risenW** [datopian/portal.js#73]
The `portal cli` can automatically display dataset page with information when we run the command:

```
# PATH defaultso to current directory
portal [show [PATH]]
```

## Acceptance

* [x] `portal` command as a basic shell script ... **Done** https://github.com/datopian/portal-experiment/pull/11
* [x] `portal` command as a proper bundled CLI **Done** https://github.com/datopian/portal-experiment/pull/11

<img width="822" alt="Screen Shot 2021-03-03 at 4 34 26 PM" src="https://user-images.githubusercontent.com/29900845/109830755-14e0e900-7c3f-11eb-8c30-cfc09679361f.png">
<img width="701" alt="Screen Shot 2021-03-03 at 4 36 21 PM" src="https://user-images.githubusercontent.com/29900845/109830761-16aaac80-7c3f-11eb-8000-145991a21e3e.png">

https://user-images.githubusercontent.com/29900845/109830797-1dd1ba80-7c3f-11eb-908e-adf4389d5240.mov

## Tasks

* [x] Have the portal nextjs app use an ENV variable to locate the file
* [x] Add CLI app folder
* [x] Create CLI file 
  * [x]  that clones the portal repo
  * [x] installs portal
  * [x] exports the dataset folder
  * [x] starts the portal app  

### Starter, hacky approach

A starter, a shell script like ... this

```
cd /Users/rgrp/src/datopian/sandbox/portal
export DATASET=...
npm run dev
```

```
portal PATH
```

How it works:

```bash
cd ~/.portal/
git clone https://github.com/datopian/portal.js/
cd portal.js/packages/portal-app
# or yarn install ...
npm install
export DATASET=PATH
next dev

# watch and reload next ... (perhaps a hack by writing something into next folder to trigger reload)
# or use https://github.com/hashicorp/next-remote-watch
```
