### ISSUE TITLE
Admin to setup for work on new Portal.JS (Feb 2021)

### ISSUE THREAD

**Issue by rufuspollock** [datopian/portal.js#74]
We need to setup and "clean the decks" in prep for the re-focused Portal.JS as of Feb 2021.

## Acceptance

* [x] Clear on where we are working on things **We are focused in this portal.js repo**
* [x] Old issues tidied and cleared up **DONE. Issue list is clean (empty)!**

## Tasks

* [x] Agree on repo we are using **DONE. https://github.com/datopian/portal.js** (Follow up in #59)
* [x] Enable discussions **DONE. Discussions are enabled and first discussion created https://github.com/datopian/portal.js/discussions/63**
* [x] clean out old issues **DONE. Have moved a couple to discussions #58 and #37 and closed rest (largely as invalid).**

## Analysis

Existing outstanding issues

![image](https://user-images.githubusercontent.com/180658/110849348-6cbac800-82af-11eb-88fc-e56c2bfa56a3.png)

**Comment by rufuspollock** [comment]
FIXED. All done. Also closed the current project https://github.com/datopian/portal.js/projects/1
